name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/seasonbarley/android_kernel_common_oneplus_sm8750
          kernel-branch: oneplus/sm8750_v_15.0.0_oneplus_13
          config: vendor/kona_defconfig
          arch: arm64
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r450784d

